services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dishly
      POSTGRES_PASSWORD: dishlypass
      POSTGRES_DB: dishly
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dishly-network

  api:
    build: ./api
    restart: on-failure
    environment:
      DATABASE_URL: postgres://dishly:dishlypass@db:5432/dishly
    depends_on:
      - db
    ports:
      - "4000:4000"
      - "5555:5555"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - dishly-network

  adminer:
    image: adminer
    container_name: dishly-adminer
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - dishly-network

  client:
    build: ./client
    restart: on-failure
    depends_on:
      - api
    ports:
      - "8081:8081"  # Metro bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo DevTools
      - "19002:19002" # Expo DevTools
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npx expo start --web
    networks:
      - dishly-network

  # nextjs:
  #   build: ./nextjs
  #   restart: on-failure
  #   depends_on:
  #     - api
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./nextjs:/app
  #   networks:
  #     - dishly-network

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - frontend
  #     - api
  #   networks:
  #     - dishly-network

volumes:
  pgdata:

networks:
  dishly-network:
    driver: bridge
