services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dishly
      POSTGRES_PASSWORD: dishlypass
      POSTGRES_DB: dishly
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dishly-network

  api:
    build: ./api
    restart: on-failure
    environment:
      DATABASE_URL: postgres://dishly:dishlypass@db:5432/dishly
    depends_on:
      - db
    ports:
      - "4000:4000"
      - "5555:5555"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - dishly-network

  adminer:
    image: adminer
    container_name: dishly-adminer
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - dishly-network

  frontend:
    build: ./frontend
    restart: on-failure
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - dishly-network

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - frontend
  #     - api
  #   networks:
  #     - dishly-network

volumes:
  pgdata:

networks:
  dishly-network:
    driver: bridge
