@startuml architecture


node "Frontend" {
    component Client [
        App Expo + React-Native
        node:20-alpine
    ]
}

node "Middleware" {
    component Auth[
        App Expo + React-Native
        node:20-alpine
    ]
}

node "Backend" {
    component Trip [
        Trip_service
        node:20-alpine
    ]
    component User [
        User_service
        node:20-alpine
    ]

    component Resa [
        Reservation_service
        node:20-alpine
    ]

    component Review [
        Review_service
        node:20-alpine
    ]
    
    port API 
    API - [Trip]
    API - [Auth]
    API - [Resa]
    API - [Review]
}

database "PostgreSQL" as pgsql {
    component Trip_DB [
        Trip_DB
        postgis/postgis:13-master
    ]
    component User_DB [
        User_DB
        postgis/postgis:13-master
    ]
    component Reservation_DB [
        Reservation_DB
        postgis/postgis:13-master
    ]
    component Review_DB [
        Review_DB
        postgis/postgis:13-master
    ]
}

[Client] --- API

[Auth] -down- [User]

[Trip_DB] -up-[Trip]
[User_DB] -up- [User]
[Reservation_DB] -up- [Resa]
[Review_DB] -up- [Review]

[Prisma:latest] --- [pgsql]

@enduml