@startuml
' skinparam linetype ortho

entity "User" {
    id
  --
    lastname : string
    firstname : string
    email : string
    password : string
    role_id : <<FK>> number
}

entity "Role" {
    id
  --
    type: string
}

entity "Recipe" {
    id
  --
    title : string
    image : string
    servings : number
    ingredients : <<FK>> number
    tags : <<FK>> number
    categories: <<FK>> number
    user_id : <<FK>> number
    steps : <<FK>> number
}

entity "Ingredient" {
    id
  --
    name : string
}

entity "RecipeIngredient" {
    id
  --
    amount : number
ingredient_id : <FK>> number
unit : <<FK>> number
}

entity "Unit" {
    id
  --
    name : string
}

entity "Tag" {
    id
  --
    name : string
}

entity "Category" {
    id
  --
    name : string
}

entity "Step" {
    id
  --
    description : string
    image : string
}

User }|--|| Role
User ||--o{ Recipe
Recipe ||--|{ RecipeIngredient
Recipe }o--o{ Tag
Recipe }o--|{ Category
Recipe ||--|{ Step
RecipeIngredient }o--|| Ingredient
RecipeIngredient }o--|| Unit


@enduml